/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "release-notes",
    {
      type: "category",
      label: "About Rancher",
      link: {
        type: 'doc',
        id: "rancher-manager",
      },
      items: [
        "getting-started/quick-start-guides/deploy-rancher-manager/prime",
        "getting-started/overview",
        "reference-guides/rancher-manager-architecture/rancher-manager-architecture",
        "reference-guides/kubernetes-concepts",
        "glossary"
      ]
    },
    {
      type: "category",
      label: "Prime Installation and Upgrades",
      items: [
        "getting-started/installation-and-upgrade/installation-requirements/installation-requirements",
        "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/install-upgrade-on-a-kubernetes-cluster",
        "reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration",
        "getting-started/installation-and-upgrade/installation-references/installation-references",
        "getting-started/installation-and-upgrade/other-installation-methods/other-installation-methods",
        "getting-started/installation-and-upgrade/resources/resources",
        "how-to-guides/advanced-user-guides/tune-etcd-for-large-installs",
        "getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes",
        "getting-started/installation-and-upgrade/upgrade-kubernetes-without-upgrading-rancher",
        "integrations-in-rancher/cloud-marketplace/cloud-marketplace"
      ]
    },
    {
      type: "category",
      label: "Rancher Administration",
      items: [
        "how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-permissions-and-global-configuration",
        "how-to-guides/new-user-guides/kubernetes-cluster-setup/kubernetes-cluster-setup",
        "reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration",
        "how-to-guides/new-user-guides/add-users-to-projects",
        "reference-guides/user-settings/user-settings",
        "how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/backup-restore-and-disaster-recovery",
        {
          type: "category",
          label: "Backups and Restore Configuration Reference",
          link: {
            type: 'doc',
            id: "reference-guides/backup-restore-configuration/backup-restore-configuration",
          },
          items: [
            "reference-guides/backup-restore-configuration/backup-configuration",
            "reference-guides/backup-restore-configuration/restore-configuration",
            "reference-guides/backup-restore-configuration/storage-configuration",
            "reference-guides/backup-restore-configuration/examples"
          ]
        },
        "how-to-guides/advanced-user-guides/enable-experimental-features/enable-experimental-features",
        "reference-guides/best-practices/rancher-server/rancher-server"
      ]
    },
    {
      type: "category",
      label: "Cluster Administration",
      items: [
        "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/kubernetes-clusters-in-rancher-setup",
        "how-to-guides/new-user-guides/manage-clusters/manage-clusters",
        "how-to-guides/new-user-guides/launch-kubernetes-with-rancher/about-rancher-agents",
        "how-to-guides/new-user-guides/infrastructure-setup/infrastructure-setup",
        "reference-guides/cluster-configuration/downstream-cluster-configuration/downstream-cluster-configuration",
        "how-to-guides/new-user-guides/launch-kubernetes-with-rancher/launch-kubernetes-with-rancher",
        "how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-resources-setup",
        "how-to-guides/new-user-guides/manage-namespaces",
        "how-to-guides/advanced-user-guides/manage-projects/manage-projects",
        "how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher",
        "reference-guides/best-practices/rancher-managed-clusters/rancher-managed-clusters",
        {
          type: "category",
          label: "Downstream Hosted Cluster Setup",
          items: [
            "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/set-up-cloud-providers",
            "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/kubernetes-clusters-in-rancher-setup",
            {
              type: "category",
              label: "Azure Kubernetes Service (AKS)",
              items: [
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks",
                "reference-guides/cluster-configuration/rancher-server-configuration/aks-cluster-configuration",
                "reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/azure",
                "reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/azure"
              ]
            },
            {
              type: "category",
              label: "Amazon Elastic Kubernetes Service (EKS)",
              items: [
                // Is this a mistake? The same page is linked for EC2 as well
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon",
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-amazon",
                "reference-guides/cluster-configuration/rancher-server-configuration/eks-cluster-configuration"
              ]
            },
            {
              type: "category",
              label: "Amazon Elastic Compute Cloud (EC2)",
              items: [
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon",
                "reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/amazon-ec2",
                "reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/amazon-ec2",
                "how-to-guides/new-user-guides/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups"
              ]
            },
            {
              type: "category",
              label: "Google Kubernetes Engine (GKE)",
              items: [
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke",
                "reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-cluster-configuration"
              ]
            },
            {
              type: "category",
              label: "Google Cloud Service (GCS)",
              items: [
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/google-compute-engine",
              ]
            },
            {
              type: "category",
              label: "VMWare vSphere",
              items: [
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-in-tree-vsphere",
                {
                  type: "category",
                  label: "Install on VMWare vSphere",
                  items: [
                    "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-in-tree-vsphere",
                    "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-out-of-tree-vsphere",
                  ],
                },
                "how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-vsphere",
                "how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/vsphere",
                "reference-guides/cluster-configuration/downstream-cluster-configuration/node-template-configuration/vsphere"
              ]
            }
          ]
        },
      ]
    },
    {
      type: "category",
      label: "Security",
      link: {
        type: 'doc',
        id: "reference-guides/rancher-security/rancher-security",
      },
      items: [
        "reference-guides/rancher-security/security-advisories-and-cves",
        "reference-guides/rancher-security/kubernetes-security-best-practices",
        "reference-guides/rancher-security/rancher-security-best-practices",
        "integrations-in-rancher/neuvector/neuvector",
        "reference-guides/rancher-webhook",
        {
          type: "category",
          label: "Hardening Guides",
          items: [
            "reference-guides/rancher-security/hardening-guides/hardening-guides",
            "reference-guides/rancher-security/rancher-webhook-hardening"
          ]
        },
        {
          type: "category",
          label: "CIS Scans (Security Scans)",
          items: [
            "integrations-in-rancher/cis-scans/cis-scans",
            "integrations-in-rancher/cis-scans/rbac-for-cis-scans",
            "how-to-guides/advanced-user-guides/cis-scan-guides/install-rancher-cis-benchmark",
            "how-to-guides/advanced-user-guides/cis-scan-guides/uninstall-rancher-cis-benchmark",
            "integrations-in-rancher/cis-scans/configuration-reference",
            "how-to-guides/advanced-user-guides/cis-scan-guides/run-a-scan",
            "how-to-guides/advanced-user-guides/cis-scan-guides/run-a-scan-periodically-on-a-schedule",
            "how-to-guides/advanced-user-guides/cis-scan-guides/skip-tests",
            "how-to-guides/advanced-user-guides/cis-scan-guides/view-reports",
            "how-to-guides/advanced-user-guides/cis-scan-guides/enable-alerting-for-rancher-cis-benchmark",
            "how-to-guides/advanced-user-guides/cis-scan-guides/configure-alerts-for-periodic-scan-on-a-schedule",
            "how-to-guides/advanced-user-guides/cis-scan-guides/configure-alerts-for-periodic-scan-on-a-schedule"
          ]
        },
        {
          type: "category",
          label: "Pod Security",
          items: [
            "how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards",
            "how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates",
            "reference-guides/rancher-security/psa-restricted-exemptions"
          ]
        },
        {
          type: "category",
          label: "Secrets & Encryption",
          items: [
            "how-to-guides/new-user-guides/kubernetes-resources-setup/secrets",
            "getting-started/installation-and-upgrade/resources/add-tls-secrets",
            "how-to-guides/new-user-guides/kubernetes-resources-setup/encrypt-http-communication",
            "how-to-guides/new-user-guides/manage-clusters/rotate-encryption-key"
          ]
        },
      ]
    },
    {
      type: "category",
      label: "Integrations",
      link: {
        type: 'doc',
        id: "integrations-in-rancher/integrations-in-rancher"
      },
      items: [
        "integrations-in-rancher/kubernetes-distributions/kubernetes-distributions",
        "integrations-in-rancher/rancher-extensions",
        "integrations-in-rancher/harvester/harvester",
        "integrations-in-rancher/longhorn/longhorn",
        "integrations-in-rancher/cis-scans/cis-scans",
        "integrations-in-rancher/neuvector/neuvector",
        "integrations-in-rancher/kubewarden/kubewarden",
        "integrations-in-rancher/elemental/elemental",
        "integrations-in-rancher/fleet/fleet"
      ]
    },
    {
      type: "category",
      label: "Observability",
      items: [
        "reference-guides/rancher-cluster-tools",
        "reference-guides/rancher-project-tools",
        {
          type: "category",
          label: "Logging",
          items: [
            "reference-guides/best-practices/rancher-managed-clusters/logging-best-practices",
            "integrations-in-rancher/logging/logging",
            "how-to-guides/advanced-user-guides/enable-api-audit-log",
            "how-to-guides/advanced-user-guides/enable-api-audit-log-in-downstream-clusters"
          ]
        },
        {

          type: "category",
          label: "Monitoring & Dashboards",
          items: [
            "reference-guides/best-practices/rancher-managed-clusters/monitoring-best-practices",
            "integrations-in-rancher/monitoring-and-alerting/monitoring-and-alerting",
            "how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring",
            "how-to-guides/advanced-user-guides/monitoring-alerting-guides/uninstall-monitoring",
            "how-to-guides/advanced-user-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads",
            {
              type: "category",
              label: "Monitoring Configuration Reference",
              link: {
                type: 'doc',
                id: "reference-guides/monitoring-v2-configuration/monitoring-v2-configuration"
              },
              items: [
                "how-to-guides/advanced-user-guides/monitoring-v2-configuration-guides/monitoring-v2-configuration-guides",
                "reference-guides/prometheus-federator/prometheus-federator",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/prometheus-federator-guides",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/debug-high-memory-usage",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/enable-prometheus-federator",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/uninstall-prometheus-federator",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/customize-grafana-dashboards",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/prometheus-federator-guides/set-up-workloads",
              ]
            },
            {
              type: "category",
              label: "Customizing the Dashboard",
              items: [
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/customize-grafana-dashboard",
                "how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard"
              ]
            },
          ]
        },
        {
          type: "category",
          label: "Istio",
          link: {
            type: 'doc',
            id: "how-to-guides/advanced-user-guides/istio-setup-guide/istio-setup-guide"
          },
          items: [
            "reference-guides/rancher-cluster-tools",
            "reference-guides/rancher-project-tools",
          ]
        },
        {
          type: "category",
          label: "Observability Integrations",
          items: [
            "integrations-in-rancher/logging/logging",
            "integrations-in-rancher/monitoring-and-alerting/monitoring-and-alerting",
          ]
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        "api/quickstart",
        "api/workflows/projects",
        "api/api-reference",
      ]
    },
    {
      type: "category",
      label: "Troubleshooting",
      link: {
        type: 'doc',
        id: "troubleshooting/general-troubleshooting"
      },
      items: [
        "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting",
        "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/certificate-troubleshooting",
        "troubleshooting/kubernetes-components/kubernetes-components",
        "troubleshooting/other-troubleshooting-tips/rancher-ha",
        "troubleshooting/other-troubleshooting-tips/registered-clusters",
        "troubleshooting/other-troubleshooting-tips/networking",
        "how-to-guides/advanced-user-guides/open-ports-with-firewalld",
        "troubleshooting/other-troubleshooting-tips/kubernetes-resources",
        "troubleshooting/other-troubleshooting-tips/dns",
      ]
    },
    "contribute-to-rancher"
  ]
}
module.exports = sidebars;
