= Rancher Architecture

+++<head>++++++<link rel="canonical" href="https://ranchermanager.docs.rancher.com/reference-guides/rancher-manager-architecture">++++++</link>++++++</head>+++

This section focuses on the xref:rancher-server-and-components.adoc[Rancher server and its components] and how xref:communicating-with-downstream-user-clusters.adoc[Rancher communicates with downstream Kubernetes clusters].

For information on the different ways that Rancher can be installed, refer to the link:../../getting-started/installation-and-upgrade/installation-and-upgrade.md#overview-of-installation-options[overview of installation options.]

For a list of main features of the Rancher API server, refer to the link:../../getting-started/overview.md#features-of-the-rancher-api-server[overview section.]

For guidance about setting up the underlying infrastructure for the Rancher server, refer to the xref:architecture-recommendations.adoc[architecture recommendations.]

:::note

This section assumes a basic familiarity with Docker and Kubernetes. For a brief explanation of how Kubernetes components work together, refer to the xref:../kubernetes-concepts.adoc[concepts] page.

:::
