= Adding a Pod Security Policy

+++<head>++++++<link rel="canonical" href="https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/add-a-pod-security-policy">++++++</link>++++++</head>+++

:::note Prerequisite:

The options below are available only for clusters that are xref:../launch-kubernetes-with-rancher/launch-kubernetes-with-rancher.adoc[launched using RKE.]

:::

When your cluster is running pods with security-sensitive configurations, assign it a xref:../authentication-permissions-and-global-configuration/create-pod-security-policies.adoc[pod security policy], which is a set of rules that monitors the conditions and settings in your pods. If a pod doesn't meet the rules specified in your policy, the policy stops it from running.

You can assign a pod security policy when you provision a cluster. However, if you need to relax or restrict security for your pods later, you can update the policy while editing your cluster.

. Click *☰ > Cluster Management*.
. Go to the cluster to which you want to apply a pod security policy and click *⋮ > Edit Config*.
. From *Pod Security Policy Support*, select *Enabled*.
+
:::note
+
This option is only available for clusters xref:../launch-kubernetes-with-rancher/launch-kubernetes-with-rancher.adoc[provisioned by RKE].
+
:::

. From the *Default Pod Security Policy* drop-down, select the policy you want to apply to the cluster.
+
Rancher ships with link:../authentication-permissions-and-global-configuration/create-pod-security-policies.md#default-psps[policies] of `restricted` and `unrestricted`, although you can link:../authentication-permissions-and-global-configuration/create-pod-security-policies.md#creating-psps[create custom policies] as well.

. Click *Save*.

*Result:* The pod security policy is applied to the cluster and any projects within the cluster.

:::note

Workloads already running before assignment of a pod security policy are grandfathered in. Even if they don't meet your pod security policy, workloads running before assignment of the policy continue to run.

To check if a running workload passes your pod security policy, clone or upgrade it.

:::
