= Install Rancher CIS Benchmark
:experimental:

+++<head>++++++<link rel="canonical" href="https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/cis-scan-guides/install-rancher-cis-benchmark">++++++</link>++++++</head>+++

. In the upper left corner, click *☰ > Cluster Management*.
. On the *Clusters* page, go to the cluster where you want to install CIS Benchmark and click *Explore*.
. In the left navigation bar, click menu:Apps[Charts].
. Click *CIS Benchmark*
. Click *Install*.

*Result:* The CIS scan application is deployed on the Kubernetes cluster.

:::note

If you are running Kubernetes v1.24 or earlier, and have a xref:../../new-user-guides/authentication-permissions-and-global-configuration/create-pod-security-policies.adoc[Pod Security Policy] (PSP) hardened cluster, CIS Benchmark 4.0.0 and later disable PSPs by default. To install CIS Benchmark on a PSP-hardened cluster, set `global.psp.enabled` to `true` in the values before installing the chart. xref:../../new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.adoc[Pod Security Admission] (PSA) hardened clusters aren't affected.

:::
